const titoli = ['Cannizzaro Catania', 'Policlinico di Bari', ' Cardarelli di Napoli','Policlinico Gemelli Roma',
'Careggi Firenze','San Martino di Genova','San Raffaele Milano','Molinette di Torino','Policlinico Sant’Orsola di Bologna'];

const immagini = ['Cannizzaro.jpg', 'Bari.jpg', 'Napoli.jpg','Roma.jpg',
'Firenze.jpg','Genova.jpg','Milano.jpg','Torino.jpg','Bologna.jpg'];

const descrizioni = ['Azienda di Riferimento regionale per l’emergenza-urgenza. Sede di strutture di alta specializzazione, dotata di tecnologie diagnostico-terapeutiche avanzate ed innovative. ', 'Azienda Ospedaliero-Universitaria polispecialistica, una delle piu complete del meridione costituita da numerose unità operative di area medica e chirurgica.', 'Azienda Ospedaliero-Universitaria di alta specializzazione, che opera a beneficio di utenti di un ampio territorio, che interessa, oltre alla città, anche la provincia ed la regione Campania intera e rappresenta un punto di riferimento per altre regioni d’Italia meridionale.','Azienda di rilievo a livello nazionale e internazionale costituita dalla Fondazione Policlinico Universitario Agostino Gemelli IRCCS, nata nel 2015, è articolata tra Consiglio di Amministrazione, Direzione Generale, Comitato Scientifico IRCCS, Collegio dei Revisori dei Conti, Organismo di Vigilanza, Comitato Etico e Comitato di Consulenza clinica, didattica e scientifica', 'Azienda ospedaliera multidisciplinare che ha della salute fisica, psichica e sociale il suo target principale attraverso un processo che includa in modo inscindibile la didattica, come strumento di costruzione e miglioramento delle competenze degli operatori e dei soggetti in formazione e la ricerca, volta al continuo progresso delle conoscenze cliniche e biomediche.', ' Ha cinque secoli di storia e ha raggiunto un alto livello qualitativo delle prestazioni. Si tratta di un importante centro di riferimento con tipologia organizzativa degli Istituti di Ricovero e cura a carattere scientifico IRCCS. Grande prestigio è attribuito alla area oncologica che è caratterizzata dalla capacità di integrazione sia della assistenza e della cura, sia della formazione e ricerca, prevalentemente traslazionale.'
,'Il San Raffaele è un Istituto di Ricovero e Cura a Carattere Scientifico e un policlinico universitario di rilievo internazionale e di alta specializzazione, fondato per fornire cure specializzate e contribuire allo sviluppo di nuove terapie per molte patologie.L’eccellenza medico-scientifica dell’Ospedale nasce dalla triplice identità dell’istituto, un luogo dove ricerca, clinica e formazione universitaria interagiscono quotidianamente.', 'Il Presidio è un"azienda multispecialistica di eccellenza, integrata con l"Università degli Studi di Torino e impegnata a svolgere attività di assistenza, insegnamento e ricerca, costituendo quindi al tempo stesso elemento strutturale del Servizio Sanitario Nazionale, e in particolare del Servizio Sanitario della Regione Piemonte, e del sistema universitario.Fornisce servizi di diagnostica e di cura a livello ambulatoriale, in regime di ricovero o tramite Pronto Soccorso.', 'L’Azienda Ospedaliero-Universitaria di Bologna Policlinico S. Orsola - Malpighi è un ospedale molto antico (il primo nucleo risale al 1592) ed è sede della Facoltà di Medicina e Chirurgia dell’Università Alma Mater Studiorum di Bologna. Si colloca nel cuore della città di Bologna con un’estensione di circa 1,8 Km e un’organizzazione logistica che si struttura in 27 Padiglioni che ospitano le Unità Operative del Policlinico. Centro di riferimento nazionale ed internazionale per diverse patologie; ogni anno sono organizzati, nelle sue sedi interne, eventi didattico-formativi ai quali partecipano professionisti di fama nazionale e internazionale.'];



const citta = ['Catania', 'Bari', 'Napoli','Roma','Firenze','Genova','Milano','Torino','Bologna'];

const latitudine=[37.543588844697716,41.11303849270135,40.86645768391178,41.9325865359911,43.80736577408041,44.40886193953808, 45.50983336758059,45.05017046729903,44.491399962806106];


const longitudine=[15.118432699966904, 16.86194120500303, 14.22589533091826, 12.429164210852655, 11.247912337566119, 8.974863559756404, 9.2657227, 7.672506691501589, 11.361527297304784];


const zoom=[17, 17, 16, 17, 16 , 17, 16, 16, 16];
